name: Deploy Spring Boot to EC2 (Ubuntu)

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Copy .war to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: target/demo-0.0.1-SNAPSHOT.war
          target: /home/ubuntu/

      - name: Deploy and configure environment on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Remover WAR anterior
            sudo rm -f /var/lib/tomcat10/webapps/ROOT.war
            sudo rm -rf /var/lib/tomcat10/webapps/ROOT

            # Mover nuevo WAR y asignar permisos
            sudo mv /home/ubuntu/demo-0.0.1-SNAPSHOT.war /var/lib/tomcat10/webapps/ROOT.war
            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/ROOT.war
            sudo chmod 755 /var/lib/tomcat10/webapps/ROOT.war

            # Configurar variables de entorno (se aplican al reiniciar Tomcat)
            echo 'SPRING_MAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}' | sudo tee /etc/environment
            echo 'SPRING_DATASOURCE_URL=${{ secrets.DB_URL }}' | sudo tee -a /etc/environment
            echo 'SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }}' | sudo tee -a /etc/environment
            echo 'SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }}' | sudo tee -a /etc/environment

            # Reiniciar Tomcat
            sudo systemctl restart tomcat10
